#!/usr/bin/env python3
"""Deterministic generator for the gLMBench tiny RNAGym fixture.

Produces 3 toy assays (~20 substitution-only variants each, equal length) across **two RNA
types** plus a committed sha256 manifest. This is what CI runs the RNAGym data-layer and task
tests against: it needs no network and is a few KB. Re-run to regenerate; the manifest pins
hashes.

The two RNA types (``mRNA-coding`` × 2 assays, ``Non-coding`` × 1) make the upstream
**type-mean** macro genuinely differ from a plain mean over assays, so a wrapper bug that did
a flat mean instead of the upstream type-mean would be caught.

    python3 tests/data/rnagym_tiny/_generate.py
"""

from __future__ import annotations

import csv
import hashlib
import random
from pathlib import Path

HERE = Path(__file__).resolve().parent
BASES = "ACGT"
# A clean ORF: ATG start, sense codons only (no internal TAA/TAG/TGA), TAA stop.
WT_CDS = (
    "ATG"
    "GCAAAGCTGGTTGAACGTTTCCAGGACATCGGTAAACCGTTCGCAGCTGGTCTGGAAAAA"
    "TAA"
)


def _mutate(seq: str, pos: int, new: str) -> str:
    return seq[:pos] + new + seq[pos + 1 :]


def make_assay(wt: str, n: int, seed: int) -> list[dict[str, str]]:
    rng = random.Random(seed)
    rows: list[dict[str, str]] = []
    # One wild-type row (NaN mutant) — exercises the WT-drop contract.
    rows.append({"mutant": "", "sequence": wt, "DMS_score": "1.0"})
    seen: set[int] = set()
    # Substitution-only single-nt variants (equal length → mean≡sum rank).
    while len(rows) < n + 1:
        pos = rng.randrange(3, len(wt) - 3)  # keep start/stop intact
        if pos in seen:
            continue
        seen.add(pos)
        old = wt[pos]
        new = rng.choice([b for b in BASES if b != old])
        var = _mutate(wt, pos, new)
        # Synthetic fitness: deterministic function of position + base so the ranking
        # is stable and reproducible (not a real measurement).
        score = round(0.5 + 0.3 * ((pos * 7 + BASES.index(new)) % 11) / 11.0, 4)
        rows.append(
            {"mutant": f"{old}{pos + 1}{new}", "sequence": var, "DMS_score": str(score)}
        )
    return rows


def write_csv(path: Path, rows: list[dict[str, str]]) -> str:
    with open(path, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=["mutant", "sequence", "DMS_score"])
        w.writeheader()
        w.writerows(rows)
    return hashlib.sha256(path.read_bytes()).hexdigest()


def main() -> None:
    # (dms_id, rna_type, n_variants, seed)
    assays = [
        ("TOY1_ECOLX_synthetic", "mRNA-coding", 20, 1),
        ("TOY2_ECOLX_synthetic", "mRNA-coding", 18, 2),
        ("TOY3_NONCODE_synthetic", "Non-coding", 16, 3),
    ]
    lines = [
        "# gLMBench tiny RNAGym fixture (synthetic, NOT real RNAGym data).",
        "# Generated by tests/data/rnagym_tiny/_generate.py. The data-layer integrity",
        "# gate diffs each file's sha256 against this manifest.",
        'source: "synthetic tiny fixture for CI"',
        "processed_dir: .",
        "assays:",
    ]
    for name, rna_type, n, seed in assays:
        rows = make_assay(WT_CDS, n, seed)
        digest = write_csv(HERE / f"{name}.csv", rows)
        n_var = sum(1 for r in rows if r["mutant"])
        lines += [
            f"  - dms_id: {name}",
            f"    file: {name}.csv",
            f'    rna_type: "{rna_type}"',
            f"    sha256: {digest}",
            f"    n_rows: {len(rows)}",
            f"    n_variants: {n_var}",
            f"    cds_len: {len(WT_CDS)}",
        ]
        print(f"[write] {name}.csv: {len(rows)} rows ({n_var} variants), sha256={digest[:12]}…")
    (HERE / "tiny_manifest.yaml").write_text("\n".join(lines) + "\n")
    print(f"[done] {HERE / 'tiny_manifest.yaml'}")


if __name__ == "__main__":
    main()
