#!/usr/bin/env python3
"""One-time fetcher for the DGEB EC-classification DNA dataset (gLMBench data layer).

Mirrors ``scripts/fetch_bacbench_essentiality.py``: downloads the upstream HuggingFace
dataset at a pinned revision, writes one compact per-split CSV (``entry, sequence, label``;
gitignored heavy cache) with sequences U→T/upper-normalized once, and (re)emits the
sha256-pinned ``manifest.yaml`` that the task's integrity gate diffs against.

Source: ``tattabio/ec_classification_dna`` (DGEB, Apache-2.0), columns ``Entry`` /
``Sequence`` / ``Label``. Run ONCE on a box where HuggingFace is reachable
(``pip install datasets``):

    python scripts/fetch_dgeb_ec_dna.py                 # train + test
    python scripts/fetch_dgeb_ec_dna.py --splits test   # one split
    python scripts/fetch_dgeb_ec_dna.py --data-dir /tmp/ec   # write elsewhere

The committed manifest is what makes the integrity gate real: a unit test loads via the
manifest and the real run verifies each split file's sha256 against it.
"""

from __future__ import annotations

import argparse
import csv
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = REPO_ROOT / "src" / "glmbench" / "tasks" / "data" / "dgeb_ec_dna"
SRC_DIR = REPO_ROOT / "src"

HF_DATASET = "tattabio/ec_classification_dna"
HF_REVISION = "cd61c74b4930cf9f1963e6d73ff7f14e2c8e74dd"
UPSTREAM_LICENSE = "DGEB Apache-2.0"
N_LABEL_CLASSES = 128
SPLITS = ("train", "test")

# Make the in-repo data layer importable for the verbatim normalization + sha256.
sys.path.insert(0, str(SRC_DIR))
from glmbench.tasks.dgeb_ec_data import (  # noqa: E402
    preprocess_sequence,
    sha256_file,
)


def _write_split_csv(path: Path, rows: list[dict]) -> dict[str, object]:
    """Write ``entry,sequence,label`` for one split; return its stats."""
    path.parent.mkdir(parents=True, exist_ok=True)
    n_rows = 0
    labels: set[str] = set()
    lengths: list[int] = []
    with open(path, "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["entry", "sequence", "label"])
        for row in rows:
            entry = str(row.get("Entry") or row.get("entry") or "").strip()
            label = str(row.get("Label") or row.get("label") or "").strip()
            seq = preprocess_sequence(str(row.get("Sequence") or row.get("sequence") or ""))
            if not entry or not label or not seq:
                continue  # drop degenerate rows (loud count via n_rows mismatch in manifest)
            w.writerow([entry, seq, label])
            n_rows += 1
            labels.add(label)
            lengths.append(len(seq))
    return {
        "n_rows": n_rows,
        "n_classes": len(labels),
        "min_len": min(lengths) if lengths else 0,
        "max_len": max(lengths) if lengths else 0,
        # Keep the exact numerator beside the count so a combined average over
        # train and test is weighted from integers, not from rounded split means.
        "total_nt": sum(lengths),
        "avg_len": sum(lengths) / len(lengths) if lengths else 0.0,
    }


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--splits", nargs="+", default=list(SPLITS), choices=list(SPLITS))
    ap.add_argument(
        "--data-dir",
        type=Path,
        default=DATA_DIR,
        help="where to write the CSVs + manifest (default: the task's data directory).",
    )
    args = ap.parse_args(argv)
    data_dir: Path = args.data_dir

    from datasets import load_dataset  # lazy — only the fetch needs HF datasets

    data_dir.mkdir(parents=True, exist_ok=True)
    manifest_lines = [
        "# DGEB EC classification (DNA) — vendored manifest (gLMBench data layer).",
        "# Generated by scripts/fetch_dgeb_ec_dna.py. DO NOT EDIT BY HAND.",
        "# The integrity gate diffs each split file's sha256 against this.",
        f'source: "{HF_DATASET} (HuggingFace), {UPSTREAM_LICENSE}"',
        f'revision: "{HF_REVISION}"',
        'citation: "DGEB: Diverse Genomic Embedding Benchmark (bioRxiv 2024.07.10.602933)."',
        f"n_label_classes: {N_LABEL_CLASSES}",
        "splits:",
    ]
    for split in args.splits:
        ds = load_dataset(HF_DATASET, split=split, revision=HF_REVISION)
        rows = list(ds)
        fpath = data_dir / f"ec_classification_dna_{split}.csv"
        stats = _write_split_csv(fpath, rows)
        digest = sha256_file(fpath)
        manifest_lines += [
            f"  - name: {split}",
            f"    file: ec_classification_dna_{split}.csv",
            f"    sha256: {digest}",
            f"    n_rows: {stats['n_rows']}",
            f"    n_classes: {stats['n_classes']}",
            f"    min_len: {stats['min_len']}",
            f"    max_len: {stats['max_len']}",
            f"    total_nt: {stats['total_nt']}",
            f"    avg_len: {stats['avg_len']}",
        ]
        print(
            f"[write] {fpath.name}: {stats['n_rows']} rows, {stats['n_classes']} classes, "
            f"len[{stats['min_len']}..{stats['max_len']}] avg {stats['avg_len']:.3f}, "
            f"total {stats['total_nt']} nt, "
            f"sha256={digest[:12]}…"
        )

    (data_dir / "manifest.yaml").write_text("\n".join(manifest_lines) + "\n")
    print(f"[done] manifest → {data_dir / 'manifest.yaml'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
